---
- hosts: debian
  gather_facts: no

  tasks:
    - name: Platzbedarf der Root-Partition ermitteln
      command: df -h /
      changed_when: false
      register: df_cmd

    - debug:
        msg: '{{df_cmd.stdout_lines}}'
