---
- hosts: localhost
  gather_facts: no

  vars:
    passwort: Supergeheim

  tasks:
    - name: sha512-Hash des Passwortes (zufällig gesalzen)
      debug: 
        msg: "{{ passwort | password_hash('sha512') }}"

    - name: Idempotenter sha512-Hash des Passwortes
      debug: 
        msg: >-
          {{ passwort |
             password_hash('sha512', 65534   | 
             random(seed=inventory_hostname) |
             string) }}
