---
- hosts: 
    - debian
    - ubuntu

  tasks:
    - name: apt-Cache aktualisieren
      apt: 
        update_cache: yes
        cache_valid_time: 3600

    - name: Alle Pakete aktualisieren
      apt: 
        upgrade: dist

    - name: Feststellen, ob ein Reboot erforderlich ist
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      reboot:
      # (Das reboot-Modul bietet auch viele Parameter!)
      when: reboot_required.stat.exists
