---
- hosts: ubuntu

  vars:
    network_name:      dbnet
    volume_name:       mariadb_data
    db_admin_password: geheim
    web_port:          8080

  tasks:
    - name: Eigenes Netzwerk anlegen
      docker_network:
        name: "{{network_name}}"

    - name: Datenvolume für MariaDB anlegen
      docker_volume:
        name: "{{volume_name}}"
  

    - name: MariaDB-Container anlegen
      docker_container:
        name: mariadb
        image: mariadb
        networks:
          - name: dbnet
        networks_cli_compatible: yes
        volumes:
          - "{{volume_name}}:/var/lib/mysql"
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: "{{db_admin_password}}"

    - name: phpMyAdmin-Container anlegen
      docker_container:
        name: pma
        image: phpmyadmin/phpmyadmin
        networks:
          - name: dbnet
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        env:
          PMA_HOST: mariadb
        published_ports:
          - '{{web_port}}:80'
