---
- hosts: [srv01,srv02,srv03,srv04,srv05,srv06,srv07,srv08,srv09,srv10]
  serial: 5

  vars:
    fail_hosts: [  srv02,srv03,srv04,srv05,   srv07,srv08,srv09,srv10]

  tasks:
    - fail:
      when: inventory_hostname in fail_hosts

    - wait_for: timeout=2

    - debug: msg="{{inventory_hostname}} ist fertig."
