---
- hosts: all
  strategy: "{{ s }}"

  tasks:
    - debug:
        msg: >
          Ausgabe:
          {{inventory_hostname}} 
          {{ lookup('pipe', 'date +%H:%M:%S') }}, gestartet"
    - wait_for:
        timeout: >
          {{ inventory_hostname | regex_search('\d+') | int }}
    - debug:
        msg: >
          Ausgabe:
          {{inventory_hostname}} 
          {{ lookup('pipe', 'date +%H:%M:%S') }}, fertig"
