---
- hosts: debian

  tasks:
    - name: Testdatei erzeugen
      copy:
        dest: /tmp/test.txt
        content: Nur ein Test
        mode: 640

    - name: Paket installieren
      apt:
        name: tmux
        state: latest
