---
- hosts: all

  tasks:
    - name: Apache auf Debian-Systemen installieren
      apt:
        name: apache2
      when: ansible_os_family == "Debian"

    - name: Apache auf CentOS-Systemen installieren
      yum:
        name: httpd
      when: ansible_os_family == "RedHat"

    - name: Apache auf SUSE-Systemen installieren
      zypper:
        name: apache2
      when: ansible_os_family == "Suse"
