---
- hosts: all

  tasks:
    - name: Parameter für Debian-Systeme
      set_fact:
        apache_package_name: apache2
      when: ansible_os_family == "Debian"

    - name: Parameter für CentOS-Systeme
      set_fact:
        apache_package_name: httpd
      when: ansible_os_family == "RedHat"

    - name: Parameter für SUSE-Systeme
      set_fact:
        apache_package_name: apache2
      when: ansible_os_family == "Suse"


    - name: Apache installieren
      package:
        name: "{{apache_package_name}}"
