---
- hosts: all

  vars:
    apache:
      Debian:
        package_name: apache2
        service_name: apache2
      RedHat:
        package_name: httpd
        service_name: httpd
      Suse:
        package_name: apache2
        service_name: apache2

  tasks:
    - name: Apache installieren
      package:
        name: "{{apache[ansible_os_family].package_name}}"

    - name: Dienst starten und in Bootprozess integrieren
      service:
        name: "{{apache[ansible_os_family].service_name}}"
        state: started
        enabled: yes
