- hosts: [debian, centos, ubuntu]

  tasks:
    - name: Pinguin-Bild herunterladen
      local_action:
        module: get_url
        url: https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png
        dest: /tmp/tux.png
      run_once: true

    - name: Auf Zielhosts verteilen
      copy:
        src: /tmp/tux.png
        dest: /var/www/html
        mode: 0644
