---
- hosts: server1.example.org

  vars:
    sprueche:
      - Fr체her Vogel f채ngt den Wurm.
      - Was H채nschen nicht lernt, lernt Hans nimmermehr.
      - Die zweite Maus kriegt den K채se.

  tasks:
    - name: Zufallsspruch
      debug: msg={{item}}
      with_random_choice: "{{sprueche}}"
