---
- hosts: all

  tasks:
    - stat:
        path: /etc/sudoers
      register: st

    - name: /etc/sudoers erweitern (falls existent)
      lineinfile:
        path: /etc/sudoers
        line: "Defaults env_keep += SSH_CONNECTION"
        insertafter: "^Defaults" 
      when: st.stat.exists

    - name: Fakten-Refresh
      setup:

    - debug: msg={{ ansible_facts['env']['SSH_CONNECTION'].split(' ')[2] }}
