---
- hosts: all

  tasks:
    - name: Fakten über alle Dienste einsammeln
      service_facts:

    - name: Ports für HTTP(S) öffnen, falls firewalld aktiv
      firewalld:
        service: "{{item}}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items: [ http, https ]
      when: >
        ansible_facts['services']['firewalld.service'] is defined
          and
        ansible_facts['services']['firewalld.service']['state'] == "running"
