---
- hosts: debian

  vars:
    users:
      - name: flink
        fullname: Fritze Flink
      - name: mustermann
        fullname: Erika Mustermann
      - name: winzig
        fullname: Willi Winzig

  tasks:
    - name: Benutzer anlegen
      user:
        name: "{{item.name}}"
        shell: /bin/bash 
        password: >-
          {{ lookup('password', 
                    '/tmp/credentials/pass_' 
                      + item.name 
                      + '.txt 
                      chars=ascii_letters,digits
                      length=8
                      encrypt=sha512_crypt')
          }}
      with_items: "{{users}}"
