---
- hosts: all
  tasks: []


- hosts: lb 
  tasks:
    - name: Private IPs+Namen in /etc/hosts eintragen
      blockinfile:
        path: /etc/hosts
        block: |
          {% for h in groups['all'] %}
          {{ hostvars[h]['ansible_ens10']['ipv4']['address'] }} {{ h }}
          {% endfor %}

    - name: haproxy installieren
      apt:
        name: haproxy
        update_cache: yes
        cache_valid_time: 3600

    - name: Konfiguration hochladen
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: reload haproxy

    - debug:
        msg: "Loadbalancer IP: {{ansible_default_ipv4.address}}"

  handlers:
    - name: reload haproxy
      service:
        name: haproxy
        state: reloaded
