---
- hosts: ubuntu

  vars:
    network_name:      dbnet
    volume_name:       mariadb_data
    remove_volume:     yes

  tasks:
    - name: Container löschen
      docker_container:
        name: "{{item}}"
        state: absent
      with_items:
        - mariadb
        - adminer

    - name: Netzwerk löschen
      docker_network:
        name: "{{network_name}}"
        state: absent

    - name: Volume löschen
      docker_volume:
        name: "{{volume_name}}"
        state: absent
      when: remove_volume | bool
