---
- hosts: localhost
  
  vars:
    anzahl: 3
    state: present

  tasks:
    - hcloud_server:
        name: "srv{{item}}"
        server_type: cx11
        location: nbg1
        image: debian-10
        ssh_keys:
          - ansible@ansible
        state: "{{state}}"
      with_sequence: start=1 end={{anzahl}} format=%02d
