---
- hosts: localhost
  tasks:
    - name: Worker rausnehmen
      haproxy:
        state: disabled
        host: "worker-{{worker}}"
        socket: /run/haproxy/admin.sock
        backend: workers
      delegate_to: lb

    - name: Worker löschen
      hcloud_server:
        name: "worker-{{worker}}"
        state: absent

    - meta: refresh_inventory
