---
- hosts: localhost

  vars:
    num_workers: 2
    ssh_key_name: ansible@ansible

  tasks:
    - name: Privates Netzwerk anlegen
      hcloud_network:
        name: network-1
        ip_range: 10.0.0.0/8
        state: present

    - name: Subnetz anlegen
      hcloud_subnetwork:
        network: network-1
        ip_range: 10.0.0.0/24
        network_zone: eu-central
        type: server
        state: present

    - name: Loadbalancer anlegen
      hcloud_server:
        name: lb
        server_type: cx11
        location: nbg1
        image: debian-10
        ssh_keys:
          - "{{ssh_key_name}}"
        state: present

    - name: Worker anlegen (worker-1, ..., worker-{{num_workers}})
      hcloud_server:
        name: "worker-{{item}}"
        server_type: cx11
        location: nbg1
        image: debian-10
        labels: 
          type: worker
        ssh_keys:
          - "{{ssh_key_name}}"
        state: present
      with_sequence: start=1 end={{num_workers}}


    - name: LB an privates Netzwerk anbinden
      hcloud_server_network:
        network: network-1
        server: lb
        ip: 10.0.0.10

    - name: Worker an privates Netzwerk anbinden
      hcloud_server_network:
        network: network-1
        server: "worker-{{item}}"
        ip: "10.0.0.{{ 100 + (item|int) }}"
      with_sequence: start=1 end={{num_workers}}


    - name: Inventory neu laden
      meta: refresh_inventory
