---
- hosts: worker-*
  gather_facts: no
  tasks:
    - wait_for_connection:


- hosts: worker-*

  tasks:
    - name: Mojolicious installieren
      apt:
        name: libmojolicious-perl
        update_cache: yes
        cache_valid_time: 3600

    - name: Applikation installieren
      copy:
        src: src/app.pl
        dest: /usr/local/bin/app.pl
        mode: 0755

    - name: systemd Unit-File installieren
      copy:
        dest: /etc/systemd/system/app.service
        content: |
          [Unit]
          Description=Demo Mojolicious app
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/app.pl prefork \
                    -l http://{{ansible_ens10.ipv4.address}}:80

          [Install]
          WantedBy=multi-user.target

    - name: systemd reload
      systemd:
        daemon_reload: yes

    - name: App starten
      service:
        name: app
        state: started
        enabled: yes
