---
- name: ansible-bender Playbook
  hosts: all
  vars:
    ansible_bender:
      base_image: python:buster
      target_image:
        name: app
        cmd: apache2 -DFOREGROUND -C"ServerName localhost"
        environment:
          APACHE_RUN_DIR: /var/run/apache2
          APACHE_PID_FILE: /var/run/apache2/apache2.pid
          APACHE_RUN_USER: www-data
          APACHE_RUN_GROUP: www-data
          APACHE_LOG_DIR: /var/log/apache2

  tasks:
    - name: Apache und Perl-CGI-Modul installieren
      apt:
        update_cache: yes
        name: 
          - apache2
          - libcgi-pm-perl

    - name: Benötigte Verzeichnisse anlegen
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - /var/run/apache2
        - /var/log/apache2

    - name: Error-Logs nach STDERR schicken
      file:
        src: /dev/stderr
        dest: /var/log/apache2/error.log
        state: link
        force: yes
        follow: no

    - name: Access-Logs nach STDOUT schicken
      file:
        src: /dev/stdout
        dest: /var/log/apache2/access.log
        state: link
        force: yes
        follow: no

    - name: Module cgi und rewrite aktivieren
      command: a2enmod {{item}}
      with_items:
        - cgi
        - rewrite

    - name: App hineinkopieren
      copy:
        src: app.pl
        dest: /usr/lib/cgi-bin
        mode: 0755
    
    - name: Interne Weiterleitung konfigurieren
      blockinfile:
        path: /etc/apache2/sites-available/000-default.conf
        block: |
          RewriteEngine On
          RewriteRule ^/$ /cgi-bin/app.pl [NC,PT]
        insertbefore: "</VirtualHost>"
