---
- hosts: ubuntu

  vars:
    docker_user:  vagrant
    project_name: mariadb-adminer
    web_port:     8080

  tasks:
    - set_fact:
        compose_project_dir: ~{{docker_user}}/adm/docker/{{project_name}}

    - name: Projektordner anlegen
      file:
        path: "{{compose_project_dir}}"
        state: directory
        owner: "{{docker_user}}"

    - name: docker-compose.yml hochladen
      template:
        src: docker-compose.yml.j2
        dest: "{{compose_project_dir}}/docker-compose.yml"
        owner: "{{docker_user}}"

    - name: Container-Verbund hochfahren
      docker_compose:
        project_src: "{{compose_project_dir}}"
        state: present
