---
- hosts: all
  
  tasks:
    - group_by: >
        key={% 
        if     dtap is defined 
           and dtap == 'test' 
           and ansible_memtotal_mb <= 1024 
         %}mem_low-test{% 
        else
         %}others{% 
        endif %}


- hosts: mem_low-test
  gather_facts: false

  tasks:
    - debug:
        msg: >-
          {{ inventory_hostname }} is a testing machine
          and has {{ ansible_memtotal_mb }} MB RAM


- hosts: others
  gather_facts: false

  tasks:
    - debug: msg="{{ inventory_hostname }} is in the 'others' group"
